spring:
  profiles:
    active: default
  application:
    name: config-server
  banner:
    location: configs/banner.txt
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          default-label: main
          clone-on-start: true
          username: ${GIT_USER}
          password: ${GIT_TOKEN}
server:
  port: 7777
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}